packages:
    - packages/**
    - playground

catalog:
    '@arethetypeswrong/cli': ^0.17.4
    '@noeldemartin/scripts': next
    '@noeldemartin/solid-utils': next
    '@noeldemartin/utils': next
    '@types/node': ^24.10.4
    eslint: ^8.57.1
    eslint-plugin-vue: ^9.33.0
    idb: ^8.0.2
    publint: ^0.3.12
    soukai: next
    soukai-bis: next
    soukai-solid: next
    vue: ^3.5.0

overrides:
    '@noeldemartin/utils': next
    soukai: next
    soukai-solid: next
