packages:
    - packages/**
    - playground
    - storybook

catalog:
    '@arethetypeswrong/cli': ^0.18.3
    '@arethetypeswrong/core': ^0.18.5
    '@intlify/unplugin-vue-i18n': ^6.0.5
    '@noeldemartin/scripts': next
    '@noeldemartin/solid-utils': next
    '@noeldemartin/testing': next
    '@noeldemartin/utils': next
    '@rdfjs/types': ^2.0.1
    '@storybook/addon-docs': ^10.6.0
    '@storybook/vue3-vite': ^10.6.0
    '@tailwindcss/forms': ^0.5.10
    '@tailwindcss/typography': ^0.5.16
    '@types/node': ^26.6.3
    fake-indexeddb: ^6.0.1
    idb: ^8.0.2
    publint: ^0.3.24
    soukai-bis: next
    storybook: ^10.6.0
    tailwindcss: ^4.1.4
    unplugin-icons: ^22.1.0
    unplugin-vue-components: ^28.4.1
    vite-plus: ^1.0.0
    vite: npm:@voidzero-dev/vite-plus-core@^1.0.0
    vue-tsc: 3.3.11 # unpin once https://github.com/vuejs/language-tools/issues/6237 is fixed.
    vue: ^3.5.0
    zod: ^4.3.4

overrides:
    '@aerogel/cli': 'workspace:*'
    '@noeldemartin/solid-utils': 'catalog:'
    '@noeldemartin/testing': 'catalog:'
    '@noeldemartin/utils': 'catalog:'
    '@types/node': 'catalog:'
    soukai-bis: 'catalog:'
    vite: 'catalog:'
    'vitepress@1>vite': ^5.4.14
    vue: 'catalog:'
    vue-tsc: 'catalog:'
    zod: 'catalog:'

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'

allowBuilds:
    core-js: true
    esbuild: true
    sharp: true
    vue-demi: true

ignoreWorkspaceCycles: true

minimumReleaseAgeExclude:
    - '@noeldemartin/*'
    - soukai-bis
    - playwright-solid
