packages:
    - packages/**
    - playground

catalog:
    '@arethetypeswrong/cli': ^0.17.4
    '@noeldemartin/scripts': next
    '@noeldemartin/solid-utils': 0.6.1
    '@noeldemartin/utils': 0.7.3
    '@types/node': ^24.10.4
    eslint: ^8.57.1
    eslint-plugin-vue: ^9.33.0
    idb: ^8.0.2
    publint: ^0.3.12
    soukai: 0.7.1
    soukai-bis: next
    soukai-solid: 0.7.1

overrides:
    '@noeldemartin/utils': 0.7.3
