name: Create Aerogel

on: [push, pull_request]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    create-aerogel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v6
              with:
                  run_install: false
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  node-version-file: '.nvmrc'
                  cache: true
            - run: pnpm install
            - name: Build packages
              run: |
                  for package in cli vite core plugin-i18n plugin-routing plugin-solid plugin-local-first playwright storybook; do
                      (cd packages/$package && pnpm build && pnpm pack)
                  done
            - name: Create app
              run: |
                  git config --global user.email "john@example.com"
                  git config --global user.name "John Doe"
                  ./packages/cli/bin/gel create app --next --local --copy
                  cd app
                  vp install
                  vp exec playwright install --with-deps chromium
            - run: vp build
              working-directory: app
            - run: vp check
              working-directory: app
            - run: vp run type-check
              working-directory: app
            - run: vp test
              working-directory: app
            - run: vp run build:storybook
              working-directory: app
            - run: vp run e2e:test:chromium
              working-directory: app
