name: WIP

on: [push, pull_request]

jobs:
    wip:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: Publish changed packages
              run: |
                  echo "Hello!"
                  git diff-tree --no-commit-id --name-only -r HEAD
                  for package in $(git diff-tree --no-commit-id --name-only -r HEAD | grep "^packages/" | cut -d/ -f2 | sort -u); do
                    echo "Publishing $package..."
                    cd "packages/$package"
                    npm ls
                    cd ../..
                  done
                  echo "Done!"
